---
title: 'Figure 5 : sc'
output: html_document
date: "2024-10-27"
---


```{r}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(sechm)
  library(ggplot2)
  library(patchwork)
  library(scater)
  library(RColorBrewer)
  library(cowplot)
})
theme_set(theme_bw())
source("../scMultiome/GEX_analysis/functions.R")
source("../functions/functions.R")
options(ggrastr.default.dpi=600)
```

```{r}
sce <- readRDS("../scMultiome/GEX_analysis/neuronal.SCE.rds")
sce$celltype2 <- sub("/","\n",sce$celltype)
sce$celltype2 <- factor(sce$celltype2, sort(unique(sce$celltype2)))
sce$celltype <- factor(sce$celltype, sort(as.character(unique(sce$celltype))))
sce <- sce[,which(sce$log10sum>3.5 & sce$contamination<0.25)]

wcl <- c("ExN.CA1-do"=1, "ExN.CA1-ve-ProS"=0, "ExN.CA1-ve"=1, "ExN.Mossy"=2, "ExN.CA3-ve"=3, 
         "ExN.SUB/Cntnap4"=4, "ExN.Ccn2"=4, "ExN.IT/Tshz2"=3, "ExN.CA3-do"=5, "ExN.SUB/Fn1"=6, "InhN.Ntng1"=9, "InhN.Lamp5"=9, "InhN.Vip"=10, "InhN.Sst"=8, "InhN.Pvalb"=7, "ExN.DG"=10, "ExN.CR"=10)
tmp <- factor(sce$celltype, names(wcl))
tmp <- wcl[tmp]
sce <- sce[,order(as.integer(as.character(tmp)),sce$log10sum)]

nn <- readRDS("../scMultiome/GEX_analysis/nonNeuronal.SCE.rds")
nn <- nn[,!grepl("cycling|^CR$",nn$celltype)]
nn <- nn[,order(nn$sum)]

# atac <- readRDS("../scMultiome/ATAC/umapDt.rds")
# atac <- SingleCellExperiment(list(), reducedDims=list(UMAP=atac[,paste0("umap_",1:2)]), colData=atac)
# colnames(atac) <- atac$rn
# atac <- atac[,order(atac$celltype!="vascular")]
# atac$celltype <- sub("/","\n",atac$celltype)

ctcols <- c("ExN.CA1-do"="#4C005C", "ExN.CA1-ve"="#0075DC", "ExN.CA1-ve-ProS"="#F0A0FF", "ExN.CA3-do"="#005C31", 
"ExN.CA3-ve"="#9DCC00", "ExN.Ccn2"="#FFA8BB", "ExN.CR"="#191919", "ExN.DG", "ExN.IT/Tshz2"="#00998F", 
"ExN.Mossy"="#993F00", "ExN.SUB/Cntnap4"="#FFCC99", "ExN.SUB/Fn1"="#C20088", "InhN.Lamp5"="#FFA405", 
"InhN.Ntng1"="#FFE100", "InhN.Pvalb"="#FF0010", "InhN.Sst"="#FF5005" , "InhN.Vip"="#990000")

an <- readRDS("../scMultiome/ATAC/sce_neuronal_atac_filtered_non_resized.rds")
atac <- as.data.frame(readRDS("../scMultiome/ATAC/umapDtNeuronal.rds"))
atac$logsum <- log10(colSums(assay(an))[atac$rn])
row.names(atac) <- atac$rn
an <- SingleCellExperiment(list(), reducedDims=list(UMAP=atac[,paste0("umap_",1:2)]), colData=atac)
colnames(an) <- atac$rn
an <- an[,colnames(an) %in% colnames(sce)]
an <- an[,which(an$logsum>=3)]
an <- an[,order(an$celltype=="ExN.CR", an$celltype %in% c("ExN.IT/Tshz2","ExN.Mossy"), an$celltype %in% c("ExN.Ccn2","ExN.SUB/Cntnap4"), an$logsum)]

atac <- readRDS("../scMultiome/ATAC/umapDtNonNeuronal.rds")
ann <- SingleCellExperiment(list(), reducedDims=list(UMAP=atac[,paste0("umap_",1:2)]), colData=atac)
colnames(ann) <- atac$rn
ann <- ann[,colnames(ann) %in% colnames(nn)]
ann <- ann[,order(ann$celltype!="vascular")]
ann$celltype <- sub("/","\n",ann$celltype)
ann$celltype2 <- colData(nn)[colnames(ann),"celltype"]
ann$broadClass <- colData(nn)[colnames(ann),"broadClass"]
```


```{r}
u1 <- plotUMAP(sce, colour_by="celltype", text_by="celltype2", point_size=0.005, text_size=3.5, rasterise=TRUE, point_alpha=0.4) + scale_color_manual(values=ctcols) +
  ggtitle("Neuronal populations (RNA)") + theme_void()  + 
  theme(legend.position = "none", plot.title=element_text(hjust=0.5))

u1b <- plotUMAP(an, colour_by="celltype", text_by="celltype", point_size=0.005, text_size=3.5, rasterise=TRUE, point_alpha=0.4) + 
  theme_void() + ggtitle("Neuronal populations (ATAC)") + scale_color_manual(values=ctcols) +
  theme(legend.position = "none", plot.title=element_text(hjust=0.5))


u2 <- plotUMAP(nn, colour_by="broadClass", text_by="celltype", point_size=0.005, text_size=3.5, rasterise=TRUE, point_alpha=0.4) + 
  ggtitle("Non-neuronal populations (RNA)") + theme_void() + 
  theme(legend.position = "none", plot.title=element_text(hjust=0.5)) 

u2b <- plotUMAP(ann, colour_by="broadClass", text_by="celltype2", point_size=0.005, text_size=3.5, rasterise=TRUE, point_alpha=0.4) + 
  theme_void() + ggtitle("Non-neuronal populations (ATAC)") +
  theme(legend.position = "none", plot.title=element_text(hjust=0.5))

uvd <- plotUMAP(sce, colour_by="vd", bins=300, hex=TRUE, summary_fun=mean) + ggtitle("ventral/dorsal") + theme_void() + 
  scale_fill_gradient2(low = "darkred", mid="grey", high = "darkblue", breaks=c(-1,1), labels=c("dorsal","ventral")) + 
  theme(plot.title=element_text(hjust=0.5)) + labs(fill="")
```



```{r}
pbe <- readRDS("../scMultiome/GEX_analysis/neuronal.excitatory.PB.rds")
pbe <- pbe[,order(pbe$TimePoint, pbe$Treatment)]
pbe <- SEtools::svacor(pbe, ~TimePoint*Treatment, n.sv=1)
pbe <- log2FC(pbe, "corrected", pbe$Treatment=="Handling" & pbe$TimePoint=="Control", isLog = TRUE)
degsE <- unique(unlist(lapply(getDEA(pbe)[2:4], FUN=function(x) row.names(x)[which(x$ihw<0.15 & abs(x$logFC)>0.5 & x$logCPM>=3)])))
hme <- sechm(pbe, c(degsE,"Egr1","Fosb","Npas4","Fos","Junb","Fkbp5"), assayName = "log2FC", gaps_at="TimePoint", row_title="Excitatory neurons", top_annotation="Treatment")

pbi <- readRDS("../scMultiome/GEX_analysis/neuronal.inhibitory.PB.rds")
pbi <- pbi[,order(pbi$TimePoint, pbi$Treatment)]
pbi <- SEtools::svacor(pbi, ~TimePoint*Treatment, n.sv=1)
pbi <- log2FC(pbi, "corrected", pbi$Treatment=="Handling" & pbi$TimePoint=="Control", isLog = TRUE)
degsI <- unique(unlist(lapply(getDEA(pbi)[2:4], FUN=function(x) row.names(x)[which(x$ihw<0.15 & abs(x$logFC)>0.5 & x$logCPM>=3)])))
degsI2 <- grep("mt-",c(degsI,"Egr1","Fosb","Fos","Junb"),invert=TRUE,value=TRUE)
hmi <- sechm(pbi, degsI2, assayName = "log2FC", gaps_at="TimePoint", row_title="Inhibitory neurons", top_annotation="Treatment")

pbn <- readRDS("../scMultiome/GEX_analysis/nonNeuronal.broad.PB.rds")
deas <- readRDS("../scMultiome/GEX_analysis/nonNeuronal.DEA.rds")
deas <- deas[which(grepl("^TimePoint",deas$Comparison) & deas$ihw<0.15 & deas$logCPM>=3 & abs(deas$logFC)>0.5),]
degsN <- split(deas$gene, deas$cluster_id)
names(nnct) <- nnct <- levels(pbn$broadClass)

getlfD <- function(pb, genes, ...){
  genes <- intersect(genes,row.names(pb))
  sl <- assays(pb)$log2FC[genes,]
  isNeg <- apply(sl, 1, FUN=function(x){
    sign(x[which.max(abs(x))])
  })
  sl <- sl*isNeg
  cbind(as.data.frame(colData(pb)[,c("Treatment","TimePoint")]),
        sum=colSums(sl), mean=colMeans(sl), n=length(genes), ...)
}

cols <- c(oligodendrocyte="#E69F00", OPC="#D55E00",
                Excitatory="#56B4E9", Inhibitory="#0072B2",
                astrocytes="#009E73", microglia="#F0E442", 
                vascular="#CC79A7")
degsN <- degsN[intersect(names(degsN), names(cols))]

d <- rbind(
  getlfD(pbe, degsE, celltype="Excitatory"),
  getlfD(pbi, degsI, celltype="Inhibitory"),
  dplyr::bind_rows(lapply(nnct, FUN=function(n){
    getlfD(pbn[,pbn$broadClass==n], degsN[[n]])
  }), .id="celltype")
)
d <- aggregate(d[,c("n","sum","mean")], d[,c("Treatment","TimePoint","celltype")], FUN=median)
d <- d[d$n>1,]
#d$Time <- c(0,15,45,180)[as.integer(d$TimePoint)]
d$Time <- c(0,1,3,6)[as.integer(d$TimePoint)]
names(cols)[1] <- "oligoden."
d$celltype <- gsub("oligodendrocyte","oligoden.",d$celltype)
p0 <- ggplot(d[d$n>1 & d$Treatment=="Handling",], aes(Time, mean, group=celltype, colour=celltype)) + geom_point(size=2) + geom_line(linewidth=1.1) + theme_bw() + scale_color_manual(values=cols) + 
  theme(legend.position = "bottom", legend.title.position = "top") + 
  scale_x_continuous(breaks=c(0,1,3,6), labels=c("0","15","45","180")) +
  labs(x="Time (min)", y="mean absolute\nlog2(foldchanges)") + ggtitle("Transcriptomic response to ARS")
```




```{r, fig.height=7, fig.width=12}
pb <- readRDS("../scMultiome/GEX_analysis/neuronal.celltype.PB.rds")
pb <- updateSEforPlots(pb, dark=TRUE)
res <- readRDS("../scMultiome/GEX_analysis/neuronal.DEA.rds")
pb <- pb[,pb$celltype %in% res$cluster_id & !grepl("CR$|Ccn2|Mossy",pb$celltype)]
pb$celltype2 <- pb$celltype
levels(pb$celltype2) <- gsub("\\.|/","\n",levels(pb$celltype2))
res$celltype <- gsub("\\.|/","\n",res$cluster_id)
resup <- res[which(res$ihw<0.05 & res$logFC>1 & res$celltype %in% unique(pb$celltype2)),]
tt <- table(resup$gene)
up <- unique(resup$gene)
up2 <- names(tt)[tt>1]
up2 <- grep("Plk2|Gm3|Rik$|Pde10a|Apbb1ip|Hbb|Hba",up2,invert=TRUE,value=TRUE)
up2 <- c(up2, c("Gadd45g","Egr3","Sdk1","Ccn1","Dusp5","Per1","Arc"))
hm <- grid.grabExpr(draw(
  sechm(pb, up2, gaps_at="celltype2", breaks=0.985,
        assayName = "log2FC", column_title_gp=gpar(fontsize = 10), row_names_gp = gpar(fontsize = 9.5),
        bottom_annotation="Treatment", heatmap_legend_param=list(legend_direction="horizontal")),
  merge=TRUE, heatmap_legend_side="bottom", annotation_legend_side="bottom"))

res3 <- res[res$gene %in% up2 & !grepl("Any|Treatment", res$Comparison),]
res3$Comparison <- factor(res3$Comparison, as.character(unique(res3$Comparison)))
levels(res3$Comparison) <- gsub("TimePoint","",levels(res3$Comparison))
ggplot(res3, aes(Comparison, gene, size=-log10(ihw), colour=logFC)) + geom_point() + 
  scale_colour_gradient2() + facet_wrap(~celltype, nrow=2) + scale_size(range=c(2,7)) +
  theme_bw() + theme(axis.text.x = element_text(angle=90)) +
  labs(x=NULL, y="Genes significant in more than one cell type")
```

(all neuronal DEGs are also found in bulk...)

```{r, fig.height=7, fig.width=12}
npb <- readRDS("../scMultiome/GEX_analysis/nonNeuronal.broad.PB.rds")
npb <- updateSEforPlots(npb, dark=TRUE)
nn.deas <- readRDS("../scMultiome/GEX_analysis/nonNeuronal.DEA.rds")
nn.deas <- nn.deas[order(nn.deas$ihw),]

degs <- nn.deas[which(abs(nn.deas$logFC)>=1 & nn.deas$ihw<0.05 & nn.deas$logCPM>=3 &
                        !grepl("other_|cycling|CR|PVM",nn.deas$cluster_id)),
                c("cluster_id","gene")]
# tmp <- nn.deas[nn.deas$Comparison=="stressAny" & nn.deas$cluster_id!="OPC" & nn.deas$ihw<0.025,c("cluster_id","gene")]
# degs <- merge(degs, tmp)
tmp <- lapply(split(degs$gene, degs$cluster_id, drop=TRUE), head, n=20)
tmp$astrocytes <- head(union("Fkbp5",tmp$astrocytes),20)
hms <- lapply(sort(names(tmp)[-2]), FUN=function(x)
  sechm(npb[,npb$broadClass==x], tmp[[x]], row_title=x, gaps_at="TimePoint", 
        top_annotation=c("TimePoint","Treatment"), heatmap_legend_param=list(legend_direction="horizontal"),
        assayName="scaledLFC", name=paste0("\nscaledLFC"), breaks=0.98,
        column_title_gp=gpar(fontsize=8.5), row_names_gp=gpar(fontsize=8))
)
phm2 <- plot_grid(plotlist=lapply(hms, FUN=function(x) grid.grabExpr(draw(x, show_annotation_legend=FALSE, heatmap_legend_side="bottom"), wrap.grobs = TRUE)), nrow=1)
```


```{r, fig.width=11, fig.height=15}
pdf("Figure5.pdf", width=11, height=15)
plot_grid(
  plot_grid(u2,u1,uvd, labels=LETTERS[1:3],scale=0.9,nrow=1, rel_widths=c(4,4,5)),
  plot_grid(u2b,u1b,p0, labels=LETTERS[4:6],scale=0.9,nrow=1, rel_widths=c(4,4,5)),
  hm, phm2, nrow=4, labels=c(NA,NA,"G","H"), rel_heights=c(2.1,2.1,2.6,2.3), scale=c(1,1,0.95,0.95) )
dev.off()
```
