---
title: 'Figure 6 : sc CRS'
output: html_document
date: "2024-10-27"
---


```{r}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(sechm)
  library(ggplot2)
  library(patchwork)
  library(scater)
  library(RColorBrewer)
  library(cowplot)
})
theme_set(theme_bw())
source("../scMultiome/GEX_analysis/functions.R")
source("../functions/functions.R")
```


```{r, fig.height=12, fig.width=10}
pb <- readRDS("../scMultiome/GEX_analysis/neuronal.celltype.PB.rds")
pb <- updateSEforPlots(pb, dark=TRUE)
npb <- readRDS("../scMultiome/GEX_analysis/nonNeuronal.broad.PB.rds")
npb <- updateSEforPlots(npb, dark=TRUE)
npb$celltype <- npb$broadClass
res <- readRDS("../scMultiome/GEX_analysis/neuronal.DEA.rds")
res2 <- readRDS("../scMultiome/GEX_analysis/nonNeuronal.DEA.rds")
res <- rbind(res,res2)
res$maxlfc <- MatrixGenerics::rowMaxs(abs(as.matrix(res[,grep("logFC",colnames(res))])), na.rm=TRUE)
res2 <- res[which(grepl("treat|Restraint",res$Comparison) & (res$ihw<0.01 | (res$ihw<0.05 & res$gene %in% c("Cacna1e","Zfhx2","Apold1"))) & res$logCPM>=2 & 
                  res$maxlfc>log2(1.25) & !grepl("cycling|other|PVM|Tshz2",res$cluster_id)),]
res2$celltype <- res2$cluster_id
res2$facet <- paste0(res2$gene, " in ", gsub("ExN\\.","",res2$celltype))
res2 <- res2[order(res2$ihw),]
res2 <- dplyr::bind_rows(lapply(split(res2,res2$facet), head, n=1))

mse <- SEtools::mergeSEs(list(neuronal=pb[unique(res2$gene),], nonNeuronal=npb[unique(res2$gene),]),
                         c("logcpm","log2FC","scaledLFC"), do.scale = FALSE,
                         commonOnly = FALSE, keepRowData = FALSE)
d <- meltSE(mse, unique(res2$gene), rowDat.columns = NA)
d$gene <- d$feature
d <- merge(res2[,c("celltype","gene")], d, by=c("celltype","gene"))
d$facet <- paste0(d$gene, " in ", gsub("ExN\\.","",d$celltype))
d$Sample <- factor(d$Sample, unique(d$Sample[order(d$TimePoint,d$Treatment)]))
d2 <- reshape2::dcast(d, facet~Sample, value.var = "scaledLFC", fun.aggregate = mean)
row.names(d2) <- d2[,1]
tmp <- d[!duplicated(d$Sample),]
row.names(tmp) <- tmp$Sample
se <- SummarizedExperiment(list(scaledLFC=as.matrix(d2[,-1])), colData=tmp[colnames(d2)[-1],c("TimePoint","Treatment")])
rowData(se)$celltype <- gsub(".+ in ","",row.names(se))
metadata(se) <- metadata(pb)
h <- sechm(se, unique(d$facet[which(d$Dataset=="neuronal")]), gaps_at="TimePoint",
           column_title_gp=gpar(fontsize=11), row_title_gp=gpar(fontsize=10),
            row_names_gp=gpar(fontsize=9), gaps_row = "celltype", row_title_rot = 0, row_names_max_width = unit(1.8, "cm"), show_rownames = TRUE, width=unit(5.3,"cm"), show_heatmap_legend=FALSE, show_annotation_legend = FALSE)
h@row_names_param$anno@var_env$value <- gsub(" in .+","",h@row_names_param$anno@var_env$value)
h2 <- sechm(se, unique(d$facet[which(d$Dataset=="nonNeuronal")]), gaps_at="TimePoint", 
            column_title_gp=gpar(fontsize=11), row_title_gp=gpar(fontsize=10),
            row_names_gp=gpar(fontsize=9), gaps_row = "celltype", row_title_rot = 0, row_names_max_width = unit(1.8, "cm"), show_rownames = TRUE, width=unit(5.3,"cm"))
h2@row_names_param$anno@var_env$value <- gsub(" in .+","",h2@row_names_param$anno@var_env$value)
```

```{r, fig.height=12, fig.width=10}
cols <- c("Handling +ARS"="darkgrey", "CRS +ARS"="#0000CD96")
sel1 <- c("Fos in CA1-ve-ProS", "Fosb in CA1-ve-ProS", "Npas4 in CA1-ve-ProS", "Fkbp5 in microglia", "Egr1 in InhN.Pvalb","Cdkn1a in vascular")
sel2 <- c("Cacna1e in InhN.Pvalb", "Zfhx2 in OPC", "Pde1a in InhN.Vip", "Erbb4 in Mossy", "Vwf in vascular")
res2$sig <- paste0("FDR=",gsub("e-0", "e-", sprintf("%.0e", res2$ihw)))

plotGenes <- function(facets, nrow=1, qR=FALSE, ...){
  d2 <- d[d$facet %in% facets,]
  d2$facet <- factor(d2$facet, facets)
  res2 <- res2[which(res2$facet %in% facets),]
  ggplot(d2, aes(TimePoint, log2FC)) + 
    stat_summary(fun=mean, geom="line", linewidth=1.2,
                 aes(x=as.integer(TimePoint), group=Treatment, colour=Treatment)) + 
    geom_boxplot(aes(fill=Treatment)) + theme_bw() + scale_x_discrete() + 
    facet_wrap(~facet, nrow=nrow, scales="free_y") +
    scale_color_manual(values=cols) + scale_fill_manual(values=cols) + xlab(NULL) +
    geom_text(data=res2, aes(x=ifelse(qR,4,0.5), y=Inf, label=sig), colour="black",
              size=2.5, hjust=ifelse(qR,1,0), vjust=1.5) + 
    theme(..., axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
}

pdf("Figure6.pdf", width=10, height=12)
plot_grid(
  plot_grid(
    grid.grabExpr(draw(h, merge=TRUE)),
    grid.grabExpr(draw(h2, merge=TRUE)), nrow=1
  ),
  plotGenes(sel1, legend.position="none"), plotGenes(sel2, qR=TRUE),
  nrow=3, rel_heights = c(5,1.3,1.3), labels="AUTO", scale=0.95
)
dev.off()
```
