---
title: "S2"
output: html_document
date: "2024-11-25"
---

```{r setup}
knitr::opts_chunk$set(dev="CairoPNG")
suppressPackageStartupMessages({
  library(sechm)
  library(edgeR)
  library(stageR)
  library(ggplot2)
  library(cowplot)
  library(patchwork)
  library(clusterProfiler)
})
source("../functions/functions.R")
source("../functions/clusterProfiling.R")
th.lfc <- log2(1.2)
```

# CRS interaction foldchanges across timepoints

```{r}
se <- readRDS("../rnaDEAs/all.full.SE.rds")
se <- updateSEforPlots(se)
degs <- getDEGs(getDEA(se)[1:5], lfc.th = th.lfc)
names(tp) <- tp <- c("45min","1h30","3h")
d <- dplyr::bind_rows(lapply(tp, FUN=function(p){
  x <- getDEA(se, paste0("inter.Treatment10days.CRS.TimePoint",p))[degs,c("logFC","FDR")]
  y <- getDEA(se, paste0("inter.Treatment20days.CRS.TimePoint",p))[degs,c("logFC","FDR")]
  colnames(x) <- paste0(colnames(x),".10days")
  colnames(y) <- paste0(colnames(y),".20days")
  cbind(gene=degs,x,y)
}), .id="TimePoint")
d <- d[which((d$FDR.10days<0.05 & abs(d$logFC.10days)>log2(1.15)) | 
               (d$FDR.20days<0.05 & abs(d$logFC.20days)>log2(1.15))),]
d$TimePoint <- factor(d$TimePoint,unique(d$TimePoint))
d$minFDR <- pmin(d$FDR.10days,d$FDR.20days)
fdrbr <- c(0.01,0.0001,0.000001,10^-10)
ct <- dplyr::bind_rows(lapply(split(d,d$TimePoint), FUN=function(x){
  ct <- cor.test(x$logFC.10days, x$logFC.20days)
  data.frame(lab=paste0("r=",round(ct$estimate,2),"\np=", format(ct$p.value, digit=1)),
    logFC.10days=min(x$logFC.10days), logFC.20days=max(x$logFC.20days), TimePoint=x$TimePoint[1])
}))
ct$logFC.20days[2] <- 1.7
sp1 <- ggplot(d, aes(logFC.10days, logFC.20days)) + 
  geom_vline(xintercept=0,colour="darkgrey") + geom_hline(yintercept=0, colour="darkgrey") +
  geom_abline(slope=1,intercept=0,linetype="dashed") + geom_smooth(method=MASS::rlm) +
  geom_point(aes(alpha=-log10(minFDR))) + facet_wrap(~TimePoint, scales="free") + mytheme() +
  labs(x="CRS:ARS Interaction logFC (10days)", y="CRS:ARS Interaction\nlogFC (20days)", alpha="FDR") +
  scale_alpha_continuous(breaks=-log10(fdrbr), labels=format(fdrbr,scipen=0)) +
  geom_text(data=ct, aes(label=lab), hjust=0, vjust=1)
```


# Clustering

```{r}
se <- updateSEforPlots(se)
se <- se[,se$TimePoint !="24h"]
gl <- readRDS("../rnaDEAs/full.dampingClusters.rds")
cl <- readRDS("../rnaDEAs/clustering_res.rds")
cl <- cl[as.character(c(3,4,1,2,8,5,10,9,7,6))]

rowData(se)$metacluster <- NA_integer_
for(f in names(gl)) rowData(se)[gl[[f]],"metacluster"] <- f

gl2 <- list(
  "(down) not damped"=cl[["5"]],
  "(down) faster return\nto baseline"=cl[["9"]],
  "(down) ablated\nat 3h"=c(cl[["6"]],cl[["7"]])
)
for(f in names(gl2)) rowData(se)[gl2[[f]],"metacluster"] <- f
rowData(se)$metacluster <- factor(rowData(se)$metacluster, c(names(gl),names(gl2)))
hm <- grid.grabExpr(draw(sechm(se, cl, gaps_at="TimePoint", assayName = "scaledLFC", row_title_gp=gpar(fontsize=12), column_title_gp=gpar(fontsize=12), left_annotation = "metacluster", bottom_annotation="Treatment")))
```



```{r}
un <- readRDS("../rnaDEAs/all.unspliced.SE.rds")
un <- un[,!(un$TimePoint %in% c("24h","5h30"))]
un.tested <- row.names(getDEA(un)[[1]])
#un.degs <- getDEGs(un, lfc.th = 0.1, fdr.th=0.25, merge=TRUE)
#glun <- lapply(gl, intersect, y=un.degs)
glun <- lapply(gl, intersect, y=un.tested)#un.degs)
un <- updateSEforPlots(un)

hm.un <- sechm(se[,!(se$TimePoint %in% c("24h","5h30"))], glun, gaps_at="TimePoint", gaps_row="cluster", assayName="scaledLFC", bottom_annotation="Treatment", row_title_rot = 0, top_annotation=c("TimePoint","Treatment"), column_title="Full\ntranscriptome", isMult = TRUE, row_title_gp=gpar(fontsize=12), column_title_gp=gpar(fontsize=12)) + 
  sechm(un, glun, gaps_at="TimePoint", gaps_row="cluster", assayName="scaledLFC", bottom_annotation="Treatment", row_title_rot = 0, top_annotation=c("TimePoint","Treatment"), column_title="Active\ntranscription", column_title_gp=gpar(fontsize=12))
hm.un
```




```{r}
oraD <- readRDS(file="../rnaDEAs/dampingClusters_enrichments.down.rds")
oraD$Cluster <- factor(oraD$Cluster, levels(oraD$Cluster)[c(3,2,1)])


# enr.down <- ggplot(ora, aes(Cluster, pathway, size=-log10(pvalue), fill=enrichment, colour=FDR<0.05)) + 
#     geom_point(pch=21) + scale_fill_gradient2() + scale_size_continuous(range=c(2,8)) + 
#   scale_colour_manual(values=c("FALSE"="white", "TRUE"="black")) + 
#   theme_bw() + theme(axis.text.x=element_text(angle=90, hjust=1,vjust=0.5), axis.text.y=element_text(size=8),
#                        axis.title=element_blank()) + labs(fill="fold-\nenrichment") +
#   ggtitle("Downregulated")
```

```{r}
en <- readRDS("../rnaDEAs/dampingClusters_enrichments.rds")
gl.ora <- en$vsResponse$ORA
sigTerms <- unique(unlist(lapply(gl.ora, FUN=function(x) head(row.names(x)[which(x$FDR<0.25)]))))
oraU <- dplyr::bind_rows(lapply(gl.ora, FUN=function(x){
  x <- x[sigTerms,]
  x$pathway <- sigTerms
  x
}), .id="Cluster")
oraU$pathway <- breakStrings(gsub("_"," ",gsub("^[A-Z]*:.*:","",oraU$pathway)))
oraU$Cluster <- factor(oraU$Cluster, names(gl))


# enr.vsStress <- ggplot(ora, aes(Cluster, pathway, size=-log10(pvalue), fill=enrichment, colour=FDR<0.05)) + 
#     geom_point(pch=21) + scale_fill_gradient2() + scale_size_continuous(range=c(2,12)) + 
#   scale_colour_manual(values=c("FALSE"="white", "TRUE"="black")) + 
#   theme_bw() + theme(axis.text.x=element_text(angle=90, hjust=1,vjust=0.5), axis.text.y=element_text(size=8), 
#                        axis.title=element_blank()) + labs(fill="fold-\nenrichment") +
#   ggtitle("Upregulated\nvs stress-responsive")
```

```{r}
gl.ora <- en$vsExpressed$regulons
sigTerms <- unique(unlist(lapply(gl.ora, FUN=function(x) head(row.names(x)[which(x$FDR<0.05)]))))
oraTF <- dplyr::bind_rows(lapply(gl.ora, FUN=function(x){
  x <- x[sigTerms,]
  x$pathway <- sigTerms
  x
}), .id="Cluster")
oraTF$pathway <- breakStrings(gsub("_"," ",gsub("^[A-Z]*:.*:","",oraTF$pathway)))
oraTF$Cluster <- factor(oraTF$Cluster, names(gl))


# enr.tfs <- ggplot(ora, aes(Cluster, pathway, size=-log10(pvalue), fill=enrichment, colour=FDR<0.05)) + 
#     geom_point(pch=21) + scale_fill_gradient2() + scale_size_continuous(range=c(2,12)) + 
#   scale_colour_manual(values=c("FALSE"="white", "TRUE"="black")) + 
#   theme_bw() + theme(axis.text.x=element_text(angle=90, hjust=1,vjust=0.5), axis.text.y=element_text(size=8), 
#                        axis.title=element_blank()) + labs(fill="fold-\nenrichment") +
#   ggtitle("TF targets\nenrichment")
```

```{r, fig.width=11, fig.height=5}
ll <- list("TF targets"=oraTF, "Upregulated vs\nstress-responsive"=oraU, "Downregulated"=oraD)
ora <- dplyr::bind_rows(ll, .id="Type")
ora$Type <- factor(ora$Type, levels=names(ll))

enrP <- ggplot(ora, aes(Cluster, pathway, size=-log10(pvalue), fill=enrichment, colour=FDR<0.05)) + 
    geom_point(pch=21) + scale_fill_gradient2() + scale_size_continuous(range=c(2,12), breaks=c(0,5,10)) + 
  scale_colour_manual(values=c("FALSE"="white", "TRUE"="black")) + facet_wrap(~Type, scale="free", nrow=1) + 
  mytheme(FALSE) + theme(axis.text.x=element_text(angle=90, hjust=1,vjust=0.5), axis.text.y=element_text(size=8), 
                       axis.title=element_blank(), axis.line=element_blank(), axis.ticks = element_blank()) +
  labs(fill="fold-\nenrichment")
enrP
```



```{r, fig.width=11, fig.height=13}
pdf("S2.pdf", width=11, height=13)
# cowplot::plot_grid(
#   sp1,
#   plot_grid(
#     plot_grid(hm, grid.grabExpr(draw(hm.un, merge=TRUE), wrap.grobs = TRUE), nrow=2, labels=c("B","C"), scale=0.95),
#     plot_grid(enr.tfs, enr.vsStress, enr.down, nrow=3, labels=LETTERS[4:6], scale=0.95), nrow=1),
#   scale=c(0.95,1), labels=c("A",NA), nrow=2, rel_heights=c(2,5,5)
# )

cowplot::plot_grid(
  sp1,
  plot_grid(hm, grid.grabExpr(draw(hm.un, show_annotation_legend=FALSE), wrap.grobs = TRUE), nrow=1, labels=c("B","C"), scale=0.95, rel_widths=c(6,4.5)),
  enrP, 
  scale=c(0.95,1,0.95), labels=c("A",NA,"D"), nrow=3, rel_heights=c(2,4.7,4.5)
)

dev.off()
```