---
title: "Supp - snRNA volcanos"
output: html_document
date: "2024-11-28"
---

```{r}
suppressPackageStartupMessages({
  library(patchwork)
  library(ggplot2)
  library(ggrastr)
  library(sechm)
})
source("../functions/functions.R")
```

```{r, fig.width=15, fig.height=20}
ne <- readRDS("../scMultiome/GEX_analysis/neuronal.DEA.rds")
nn <- readRDS("../scMultiome/GEX_analysis/nonNeuronal.DEA.rds")
dea <- dplyr::bind_rows(list(Neuronal=ne, nonNeuronal=nn), .id="Class")
dea <- dea[!grepl("Any|Restraint",dea$Comparison) & !grepl("PVM|CR|cycling|other",dea$cluster_id),]
levels(dea$Comparison) <- gsub("TimePoint","ARS",levels(dea$Comparison))
dea$Comparison <- factor(droplevels(dea$Comparison), c("ARS15min","ARS45min","ARS3h"))
dea2 <- dplyr::bind_rows(lapply(split(dea, paste(dea$Comparison,dea$cluster_id)), FUN=function(x){
  x <- x[which(x$ihw<0.05),]
  x <- x[!grepl("Gm|Rik$",x$gene),]
  head(x[order(x$ihw),],5)
}))
dea$significance <- ifelse(dea$ihw<0.05, ifelse(dea$logFC>0,"upregulated","downregulated"),"n.s.")
dea$significance <- factor(dea$significance, c("upregulated","n.s.","downregulated"))

dl <- split(dea, grepl("^ExN", dea$cluster_id) + 2*grepl("\\.CA", dea$cluster_id) + 10*grepl("^InhN", dea$cluster_id))[c("3","1","10","0")]
doOneVp <- function(dea, legend=FALSE){
  ggplot(dea, aes(logFC, -log10(ihw), colour=significance)) + geom_point_rast(size=1, raster.dpi = 150) + 
    ggrepel::geom_text_repel(data=dea2[which(dea2$cluster_id %in% unique(dea$cluster_id)),,drop=FALSE], 
                             aes(label=gene), size=3, min.segment.length = 0, color="black") +
    facet_grid(Comparison~cluster_id) + theme_bw() +
      scale_color_manual(values=setNames(c("darkred","darkgrey","darkblue"), levels(dea$significance))) +
    labs(color="significance", y="-log10(FDR)") + scale_y_sqrt(breaks=c(2,5,10)) +
      theme(legend.position=ifelse(legend,"right","none"), aspect.ratio=5/7)  
}
pp <- plot_grid(doOneVp(dl[[1]], TRUE) + coord_cartesian(xlim=c(-4,4)), doOneVp(dl[[2]]),
          doOneVp(dl[[3]]), doOneVp(dl[[4]]), nrow=4)
```

```{r, fig.width=15, fig.height=20}
pdf("SXX_snRNA_volcanosARS.pdf", width=15, height=20)
pp
dev.off()
```

# Baseline differences

```{r, fig.width=12, fig.height=12}
ne <- readRDS("../scMultiome/GEX_analysis/neuronal.DEA.rds")
nn <- readRDS("../scMultiome/GEX_analysis/nonNeuronal.DEA.rds")
dea <- dplyr::bind_rows(list(Neuronal=ne, nonNeuronal=nn), .id="Class")
dea <- dea[dea$Comparison=="TreatmentRestraint" & !grepl("PVM|CR|cycling|other",dea$cluster_id) & dea$logCPM>=2,]
dea$significance <- ifelse(dea$ihw<0.05, ifelse(dea$logFC>0,"upregulated","downregulated"),"n.s.")
dea$significance <- factor(dea$significance, c("upregulated","n.s.","downregulated"))
dea2 <- dplyr::bind_rows(lapply(split(dea, paste(dea$cluster_id)), FUN=function(x){
  x <- x[which(x$ihw<0.05),]
  x <- x[!grepl("Gm|Rik$",x$gene),]
  head(x[order(x$ihw),],5)
}))
dea1 <- dea[which(dea$cluster_id %in% unique(dea2$cluster_id)),]
p1 <- ggplot(dea1, aes(logFC, -log10(ihw), colour=significance)) + ggrastr::geom_point_rast(size=1) + 
  ggrepel::geom_text_repel(data=dea2, aes(label=gene), size=3, min.segment.length = 0, color="black") +
  facet_wrap(~cluster_id, nrow=1) + theme_bw() +
  scale_color_manual(values=setNames(c("darkblue","darkgrey","darkred"), levels(dea$significance))) +
  labs(color="significant", y="-log10(FDR)") + scale_y_sqrt(breaks=c(2,5,10)) +
      theme(axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))

# dea <- dplyr::bind_rows(list(Neuronal=ne, nonNeuronal=nn), .id="Class")
# dea <- dea[grepl(":TreatmentRestraint",dea$Comparison) & !grepl("PVM|CR|cycling|other",dea$cluster_id) & dea$logCPM>=2,]
# dea$Comparison <- paste(gsub("TimePoint","CRS: ",gsub(":TreatmentRestraint","",dea$Comparison)), "ARS")
# dea$Comparison <- factor(dea$Comparison, unique(dea$Comparison))
# dea$significance <- ifelse(dea$ihw<0.05, ifelse(dea$logFC>0,"upregulated","downregulated"),"n.s.")
# dea$significance <- factor(dea$significance, c("upregulated","n.s.","downregulated"))
# dea2 <- dplyr::bind_rows(lapply(split(dea, paste(dea$cluster_id)), FUN=function(x){
#   x <- x[which(x$ihw<0.05),]
#   x <- x[!grepl("Gm|Rik$",x$gene),]
#   head(x[order(x$ihw),],5)
# }))
# dea1 <- dea[which(paste(dea$cluster_id, dea$Comparison) %in% unique(paste(dea2$cluster_id, dea2$Comparison))),]
# p2 <- ggplot(dea1, aes(logFC, -log10(ihw), colour=significance)) + ggrastr::geom_point_rast(size=1) + 
#   ggrepel::geom_text_repel(data=dea2, aes(label=gene), size=3, min.segment.length = 0, color="black") +
#   facet_wrap(~cluster_id+Comparison, nrow=3) + theme_bw() +
#     scale_color_manual(values=c("FALSE"="darkgrey", "TRUE"="darkblue")) +
#   labs(color="significant", x="Interaction log2(FC)", y="-log10(FDR)") + scale_y_sqrt(breaks=c(2,5,10)) +
#       theme(legend.position=c(1, 0), legend.justification=c(1, 0),
#             axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))
# cowplot::plot_grid(p1, p2, nrow=2, rel_heights=c(1.1,3))

pb <- readRDS("../scMultiome/GEX_analysis/neuronal.celltype.PB.rds")
pb <- updateSEforPlots(pb)
cols <- metadata(pb)$anno_colors$Treatment
res <- ne
d <- meltSE(pb, c("Npas4","Fos"), rowDat.columns = NA)
d$cluster_id <- d$celltype


resa <- res[which(grepl("Any",res$Comparison) & res$gene %in% unique(d$feature) & res$ihw<0.05 & !grepl("Ccn2",res$cluster_id)),]
resa$feature <- resa$gene
m <- merge(d[!duplicated(d[,c("cluster_id","feature")]),], resa[resa$Comparison=="stressAny",])
m$lab <- paste0("ARS q=", format(m$ihw, digit=1),"\n",
                "CRS q=", format(merge(m[,1:2], resa[resa$Comparison=="treatAny",])$ihw, digit=1))
d <- d[which(paste(d$cluster_id,d$feature) %in% paste(m$cluster_id,m$feature)),]
npas4 <- ggplot(d, aes(TimePoint, logcpm)) + 
  stat_summary(fun=mean, geom="line", linewidth=1.2, aes(x=as.integer(TimePoint), group=Treatment, colour=Treatment))  +
  geom_boxplot(aes(fill=Treatment)) + facet_wrap(~feature+celltype2, nrow=2) + theme_bw() + labs(y="Expression log(CPM)") +
  geom_text(data=m, y=0, x=4.5, aes(label=lab), size=3, colour="black", hjust=1, vjust=0) +
  scale_color_manual(values=cols) + scale_fill_manual(values=cols) + scale_x_discrete() +
  theme(legend.position = "bottom", axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))

pdf("SXX_snRNA_baselineCRS_and_Npas4.pdf", width=12, height=12)
cowplot::plot_grid(p1, npas4, nrow=2, rel_heights=c(1,2), scale=0.95, labels = LETTERS)
dev.off()
```



